### POST LIST
POST http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiYTY5N2QyZGU1MTI5MDZkMjRlNTVkIn0sImlhdCI6MTY4OTkzODM1OX0.KUeW6b3sMUvDcYDCk_Gt90YnZjZw_2cMKX8FEGT4frw
Content-Type: application/json

{
    "name": "test",
    "description": "todo must to do",
    "isFinished": "true"
}

### GET todos
GET http://localhost:3000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiYTY5N2QyZGU1MTI5MDZkMjRlNTVkIn0sImlhdCI6MTY4OTkzODM1OX0.KUeW6b3sMUvDcYDCk_Gt90YnZjZw_2cMKX8FEGT4frw

### GET LIST
GET http://localhost:3000/todos/64ba6a742de512906d24e56a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiYTY5N2QyZGU1MTI5MDZkMjRlNTVkIn0sImlhdCI6MTY4OTkzODM1OX0.KUeW6b3sMUvDcYDCk_Gt90YnZjZw_2cMKX8FEGT4frw

### GET LIST
PATCH http://localhost:3000/todos/64ba6a742de512906d24e56a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiYTY5N2QyZGU1MTI5MDZkMjRlNTVkIn0sImlhdCI6MTY4OTkzODM1OX0.KUeW6b3sMUvDcYDCk_Gt90YnZjZw_2cMKX8FEGT4frw
Content-Type: application/json

{
    "name": "todo 1 (updated)"
}

### DELETE TODO
DELETE http://localhost:3000/todos/64ba6237b429d7abbaf53e57
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiYTY5N2QyZGU1MTI5MDZkMjRlNTVkIn0sImlhdCI6MTY4OTkzODM1OX0.KUeW6b3sMUvDcYDCk_Gt90YnZjZw_2cMKX8FEGT4frw
