### REGISTER USER
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "first_name": "Eshmat",
  "last_name": "Toshmatov",
  "username": "vineuz",
  "password": "1234"
}

### LOGIN USER
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "vineuz",
  "password": "1234"
}

### GET ME
GET http://localhost:3000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiYTY5N2QyZGU1MTI5MDZkMjRlNTVkIn0sImlhdCI6MTY4OTkzODM1OX0.KUeW6b3sMUvDcYDCk_Gt90YnZjZw_2cMKX8FEGT4frw

### PATCH ME
PATCH http://localhost:3000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiYTY5N2QyZGU1MTI5MDZkMjRlNTVkIn0sImlhdCI6MTY4OTkzODM1OX0.KUeW6b3sMUvDcYDCk_Gt90YnZjZw_2cMKX8FEGT4frw
Content-Type: application/json

{
  "first_name": "G`ishmat"
}

### DELETE ME
DELETE http://localhost:3000/users/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRiYTY5N2QyZGU1MTI5MDZkMjRlNTVkIn0sImlhdCI6MTY4OTkzODM1OX0.KUeW6b3sMUvDcYDCk_Gt90YnZjZw_2cMKX8FEGT4frw
